export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  FIXTURE_NOT_FOUND: "FIXTURE_NOT_FOUND",
  REPLACEMENT_NOT_FOUND: "REPLACEMENT_NOT_FOUND",
  REPLACEMENT_TYPE_MISMATCH: "REPLACEMENT_TYPE_MISMATCH",
  REPLACEMENT_NOT_RIGGED: "REPLACEMENT_NOT_RIGGED",
  REPLACEMENT_DMX_CONFLICT: "REPLACEMENT_DMX_CONFLICT",
  CUE_ARCHIVED_LOCKED: "CUE_ARCHIVED_LOCKED",
  REPLACEMENT_PERSIST_FAILED: "REPLACEMENT_PERSIST_FAILED"
} as const;
