export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // 应急换灯校验（按校验顺序，任一命中即中止并只报第一处）
  SWAP_FAULTY_REQUIRED: "SWAP_FAULTY_REQUIRED",
  SWAP_STANDIN_REQUIRED: "SWAP_STANDIN_REQUIRED",
  SWAP_STANDIN_NOT_READY: "SWAP_STANDIN_NOT_READY",
  SWAP_TYPE_MISMATCH: "SWAP_TYPE_MISMATCH",
  SWAP_DMX_CONFLICT: "SWAP_DMX_CONFLICT",
  SWAP_CUE_ARCHIVED: "SWAP_CUE_ARCHIVED",
  SWAP_STANDIN_ALREADY_IN_CUE: "SWAP_STANDIN_ALREADY_IN_CUE"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
